stages:
  - test
  - report

test:
  image: maven:3.9.8-jdk-11
  stage: test
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/surefire-reports/*
      - allure-results/*

report:
  image: node:14
  stage: report
  script:
    - npm install -g allure-commandline --save-dev
    - allure generate allure-results --clean -o allure-report
  artifacts:
    paths:
      - allure-report
  only:
    - master
